### ISSUE TITLE
"Failed legacy log in" error

### ISSUE THREAD

**Issue by phreaq** [tprelog/homeassistant-gmusic_player#15]
I am getting an error in HA, and the Gmusic player fails to load. When I check the logs, I see:

Failed legacy log in, check http://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.login

I have tried a new app password, same issue.

I am running HA 118.1, and have a gmusic proxy running locally.

**Comment by tprelog** [comment]
Hi @phreaq Have you had this working in the past? If so, please check you can still log into the Google Music web site.

I'm not sure if your aware but Google is killing Google Music in Dec. The shutdown is rolling out at different rates depending on where you live. For some users, Google Music has already stopped working.

You can read numerous articles on the subject by searching Google for `google music is shutting down` or something similar.

**Comment by phreaq** [comment]
Hi @tprelog, thanks for the reply.

Yes, it has been working in the past (I've been using it every night for quite some time now).

And yes, I am aware the GPM is shutting down, but as of now, I'm still able to log in and play music on it (I know it's dying, so I just use it to create playlists, then push them to YTM)

**Comment by tprelog** [comment]
The only suggestion I have ATM is if you're able, [try using the oauth login](https://unofficial-google-music-api.readthedocs.io/en/latest/reference/mobileclient.html#gmusicapi.clients.Mobileclient.oauth_login) instead of legacy. The tricky part, is getting the required credentials file.

If you happen to be one of the few people still using a virtualenv install, it is relativity easy. I had some steps laid out somewhere (for venv method), [all I can find at the moment, are located in the old appdaemon thread](https://community.home-assistant.io/t/google-music-in-ha-using-appdaemon/109983). I'm unable to link the exact section, but here's what to look for in the OP.
![image](https://user-images.githubusercontent.com/35702532/99814796-79a48780-2b17-11eb-8045-34474ef260a3.png)

Honestly, I'm not sure if there is anything I can fix here. This component just passes your credentials to the gmusicapi and the login is handled from there.

**Comment by phreaq** [comment]
thanks, but I don't believe I can go that route.... (it's a bit above my understanding)

I rolled back to 117.6 and GMusic is working again. I'm not sure what may have broken it.

**Comment by greengo1** [comment]
same issue here. Was working perfectly on 117.6.

**Comment by phreaq** [comment]
broken in 118.2 as well

**Comment by tprelog** [comment]
I'll _try to fix_ this for `0.118` - _If successful, it will be the last update I make to this component_

**This component only has a few weeks of life remaining anyways**. 

When Google Music is shutdown in December, I expect this component will completely stop working.

**Comment by phreaq** [comment]
All good things must come to an end. Understood.

It was (is) an awesome add in for HA, and I for one greatly appreciate what you've done.

**Comment by tprelog** [comment]
In other news, [here is hope for the future](https://community.home-assistant.io/t/youtube-music-media-browser/226367/17?u=troy) :tada:

**Comment by phreaq** [comment]
ya, I saw that posting, and I see you're already helping out, thanks!

**Comment by tprelog** [comment]
Google Music is gone now
