### ISSUE TITLE
Config flow for custom component in home assistant 0.96

### ISSUE THREAD

**Issue by ajfriesen** [tprelog/homeassistant-gmusic_player#2]
Will this be helpful for this component?

https://developers.home-assistant.io/docs/en/config_entries_config_flow_handler.html

**Comment by tprelog** [comment]
I wonder about that myself. It says at this time it's only for for built-in components. I think is that something used by the components that can be added from the integrations page in HA? I haven't been able to fully wrap my head around everything just yet. Right now I think this is a custom platform but still the media player component (even though as users we all call these custom components) from a dev point of view I think this would need to be an actual component (not a platform). I'm not really sure though. I've been through the dev docs only a few times and some basic stuff I can understand but there is still much I do not. I think my difficulty is because I'm also new to even just using python in general.
