### ISSUE TITLE
Failed to get URL for track:

### ISSUE THREAD

**Issue by whit-tj** [tprelog/homeassistant-gmusic_player#7]
I have been following instructions to get this working. I just installed via HACS, got the packages loaded and customized, logged in successfully (first time had error in logs for failed authentication), error log told me I needed to pick 1 of the 7 device ID's. I've now tried 2 different ones and whenever I attempt to play or turn on the gmusic player (either a station or my own playlist) I immediately get this error:
Failed to get URL for track: (fc42a0fe-fb7a-3910-9913-b2c4855bf54b)

There are no other error messages in the logs, and I can't find any details about this error in the gmusic api. Am I picking an invalid device ID? Is there an issue with this current release? Any help or tips?

**Comment by tprelog** [comment]
Nothing has changed in at least a month. Latest version should be working as far as I know.
Can you tell me please:
- are you in the US?
- are you All Access subscriber?

I've seen two other people with the same `Failed to get URL for track` error but based on the format of your song ID `fc42a0fe-fb7a-3910-9913-b2c4855bf54b` I'm not sure it's the same cause. Can you please share an error when you try to play a station as well?

I'll investigate the format of your song ID.
 
---
In the meantime, two other users have had the same issue they reported in the HA forum. I'm guessing if this is not related to the format of the song ID then your issue is the device ID.

One user was [using  invalid device ID](https://community.home-assistant.io/t/google-music-in-ha-now-as-a-media-player/119918/111?u=troy) Although it was a device id return by gmusic but it is was the long ID typically associated with a computer. Something like this:
`aXXXXXea63ef3681b3257XXXa03f1XXX2c26ecc5d0XXXXX7d02d9d12ce9XXXX`
These IDs do not work. It must be a string of 16 hex digits for Android.
A correct ID for example is something like this `21150e2000000456`

From the Google Music web page, If you log in and go to setting you can confirm how many devices are registered to your Google Music account. You must first see an android device in this list before gmusicapi will return it’s ID in the gmusic_player logs (Unfortunately there is no way from here to see what ID belongs to each device)

![image](https://user-images.githubusercontent.com/35702532/69820542-4dd61680-11cf-11ea-9886-1755c701e5f8.png)

---

The second case we discovered that [stations require AA outside the US](https://community.home-assistant.io/t/google-music-in-ha-now-as-a-media-player/119918/92?u=troy). Even though free stations are available in other countries using official Google Apps, it is not the same with unofficial gmusicapi. This could explain why stations don't work but this has nothing to do with playlists.

**Comment by whit-tj** [comment]
Thanks for the help. I am in the US. It appears the issue was using the wrong device ID. Once I used the shorter 16 hex id, it is all working great! I appreciate the help, the gmusic player has been great so far!
